// AUTO-GENERATED by tools/extract-data.mjs — do not edit by hand.
// Source of truth: reference/msp-logic.js + client-logic.js
// Regenerate with `npm run generate:data`.

import type { Brand } from '@/lib/types';

/**
 * Seed brands. `inovo` is the default tenant; `msp-security-services` is the
 * sample partner that the prototype's brand switcher demonstrated.
 *
 * Nothing brand-related may be hardcoded in a component — read these through
 * the brand context, which resolves the tenant per request by hostname.
 */
export const SEED_BRANDS: Record<string, Brand> = {
  inovo: {
    id: "inovo",
    name: "Inovo Infosec",
    legalName: "Inovois InfoSec, Inc",
    tagline: "Three Dimensional Cybersecurity",
    logo: "/assets/inovo-logo.png",
    primary: "#C5131B",
    phone: "800-598-4008 + option 1",
    incidentPhone: "800-598-4008 + option 1",
    email: "sales@inovois.com",
    address: "515 S Flower Street, 18th Floor, Los Angeles, CA 90071",
    ctaDirectLabel: "Book a discovery call",
    ctaDirectUrl: "https://calendly.com/PLACEHOLDER-inovo/discovery",
    ctaPartnerUrl: "https://calendly.com/PLACEHOLDER-inovo/partnership",
    reportCtaLabel: "Review my results with a CISO",
    poweredBy: false,
    showPartnerCta: true,
    slug: "inovo",
    hostnames: ["assess.inovois.com"],
    vertical: "cmmc",
    routing: {
      model: "direct",
      notify: ["sales@inovois.com"],
    },
    econ: {
      marginPct: 25,
      referralPct: 10,
      minClients: 1,
    },
  },
  partner: {
    id: "partner",
    name: "MSP Security Services",
    legalName: "MSP Security Services, LLC",
    tagline: "Managed IT & Security",
    logo: null,
    primary: "#0F4C81",
    phone: "(555) 010-0100",
    incidentPhone: "(555) 010-0199",
    email: "security@mspsecurityservices.example",
    address: "[PLACEHOLDER — partner address]",
    ctaDirectLabel: "Book a security review",
    ctaDirectUrl: "https://calendly.com/PLACEHOLDER-partner/review",
    ctaPartnerUrl: "",
    reportCtaLabel: "Book my security review",
    poweredBy: true,
    showPartnerCta: false,
    slug: "msp-security-services",
    hostnames: ["security.partnerdomain.example"],
    vertical: "hipaa",
    routing: {
      model: "co-delivery",
      notify: ["security@mspsecurityservices.example","sales@inovois.com"],
    },
    econ: {
      marginPct: 25,
      referralPct: 10,
      minClients: 1,
    },
  },
};

/**
 * The client assessment overrides one label for the partner brand: the
 * prototype rewrites "Book my security review" to "Book my advisory session"
 * on the client report. Reproduced here so the report copy is unchanged.
 */
export const CLIENT_REPORT_CTA_OVERRIDE: Record<string, string> = {
  partner: "Book my advisory session",
};
