// AUTO-GENERATED by tools/extract-data.mjs — do not edit by hand.
// Source of truth: reference/client-logic.js
// Regenerate with `npm run generate:data`.

import type { CsfFunction, ClientQuestion, RecTable, Tier, Vertical, Qualification } from '@/lib/types';

/** The six NIST CSF 2.0 functions, in presentation order. */
export const FNS: CsfFunction[] = [
  {
    id: "govern",
    name: "Govern",
    desc: "ownership, policy, risk",
  },
  {
    id: "identify",
    name: "Identify",
    desc: "assets, data, risk assessment",
  },
  {
    id: "protect",
    name: "Protect",
    desc: "access, encryption, people",
  },
  {
    id: "detect",
    name: "Detect",
    desc: "monitoring & visibility",
  },
  {
    id: "respond",
    name: "Respond",
    desc: "plans, notification, partners",
  },
  {
    id: "recover",
    name: "Recover",
    desc: "backups, continuity, proof",
  },
];

/** 24 questions; `{FW} {DATA} {AUD} {SYSTEMS}` are substituted from the vertical. */
export const QUESTIONS: ClientQuestion[] = [
  {
    f: "govern",
    text: "Who owns cybersecurity at the executive level?",
    help: "Not who runs IT — who is accountable for security decisions.",
    options: [
      {
        label: "A named security executive (CISO or vCISO) reporting to leadership; the board is briefed at least quarterly",
        points: 3,
      },
      {
        label: "Our IT leader owns it alongside operations",
        points: 2,
      },
      {
        label: "Our MSP or IT vendor handles it",
        points: 1,
      },
      {
        label: "No one specifically",
        points: 0,
      },
    ],
  },
  {
    f: "govern",
    text: "Do you have a current, approved set of security policies aligned to {FW}?",
    help: "",
    options: [
      {
        label: "Complete set, approved by leadership, reviewed annually, staff attest",
        points: 3,
      },
      {
        label: "Mostly written; review is irregular",
        points: 2,
      },
      {
        label: "A few documents",
        points: 1,
      },
      {
        label: "None",
        points: 0,
      },
    ],
  },
  {
    f: "govern",
    text: "How is cyber risk tracked and reported to leadership?",
    help: "",
    options: [
      {
        label: "A risk register reviewed by leadership, tied to owners and action items",
        points: 3,
      },
      {
        label: "An informal list someone maintains",
        points: 2,
      },
      {
        label: "Discussed after incidents",
        points: 1,
      },
      {
        label: "Not tracked",
        points: 0,
      },
    ],
  },
  {
    f: "govern",
    text: "Do your IT providers and vendors have documented security responsibilities — and are they reviewed?",
    help: "Your MSP, cloud providers, software vendors.",
    options: [
      {
        label: "Contracts define responsibilities; critical vendors assessed annually",
        points: 3,
      },
      {
        label: "Contracts exist; reviews are ad hoc",
        points: 2,
      },
      {
        label: "We rely on vendor reputation",
        points: 1,
      },
      {
        label: "Not defined",
        points: 0,
      },
    ],
  },
  {
    f: "identify",
    text: "Do you know where {DATA} lives — every system, file share, and SaaS application?",
    help: "",
    options: [
      {
        label: "Documented data inventory and data-flow diagram, kept current",
        points: 3,
      },
      {
        label: "Mostly known, partly documented",
        points: 2,
      },
      {
        label: "Roughly",
        points: 1,
      },
      {
        label: "No",
        points: 0,
      },
    ],
  },
  {
    f: "identify",
    text: "How current is your inventory of hardware, software, and cloud services?",
    help: "",
    options: [
      {
        label: "Automated, current, includes SaaS and shadow IT discovery",
        points: 3,
      },
      {
        label: "Maintained, mostly current",
        points: 2,
      },
      {
        label: "Partial",
        points: 1,
      },
      {
        label: "None",
        points: 0,
      },
    ],
  },
  {
    f: "identify",
    text: "When was your last formal risk assessment against {FW}?",
    help: "",
    options: [
      {
        label: "Within 12 months, independent, findings tracked to closure",
        points: 3,
      },
      {
        label: "Within 12 months, internal",
        points: 2,
      },
      {
        label: "More than a year ago",
        points: 1,
      },
      {
        label: "Never",
        points: 0,
      },
    ],
  },
  {
    f: "identify",
    text: "How are vulnerabilities found and fixed?",
    help: "",
    options: [
      {
        label: "Continuous scanning; critical findings fixed within days; tracked",
        points: 3,
      },
      {
        label: "Periodic scans; fixed eventually",
        points: 2,
      },
      {
        label: "Occasional scans",
        points: 1,
      },
      {
        label: "No scanning",
        points: 0,
      },
    ],
  },
  {
    f: "protect",
    text: "How broadly is multi-factor authentication enforced?",
    help: "Email, VPN, remote access, admin consoles, cloud apps.",
    options: [
      {
        label: "Everywhere, including admin and remote access; phishing-resistant for privileged users",
        points: 3,
      },
      {
        label: "Most systems",
        points: 2,
      },
      {
        label: "Some systems",
        points: 1,
      },
      {
        label: "Not enforced",
        points: 0,
      },
    ],
  },
  {
    f: "protect",
    text: "Who can access {DATA}, and how often is that reviewed?",
    help: "",
    options: [
      {
        label: "Role-based least privilege; access reviewed quarterly and documented",
        points: 3,
      },
      {
        label: "Role-based; reviewed annually",
        points: 2,
      },
      {
        label: "Broad access; occasional cleanup",
        points: 1,
      },
      {
        label: "Almost everyone can reach it",
        points: 0,
      },
    ],
  },
  {
    f: "protect",
    text: "Is {DATA} encrypted at rest and in transit — including laptops, mobile devices, and backups?",
    help: "",
    options: [
      {
        label: "Everywhere, with managed keys and verification",
        points: 3,
      },
      {
        label: "Most places",
        points: 2,
      },
      {
        label: "Some places",
        points: 1,
      },
      {
        label: "Unknown",
        points: 0,
      },
    ],
  },
  {
    f: "protect",
    text: "How are your people trained to recognize attacks?",
    help: "",
    options: [
      {
        label: "Onboarding plus annual training, monthly phishing simulations, results tracked",
        points: 3,
      },
      {
        label: "Annual training",
        points: 2,
      },
      {
        label: "Occasional reminder emails",
        points: 1,
      },
      {
        label: "No program",
        points: 0,
      },
    ],
  },
  {
    f: "detect",
    text: "Are security logs centralized and monitored?",
    help: "",
    options: [
      {
        label: "24/7 SOC with alerting and tuned detections",
        points: 3,
      },
      {
        label: "Logs centralized, reviewed during business hours",
        points: 2,
      },
      {
        label: "Logs exist on individual systems, not reviewed",
        points: 1,
      },
      {
        label: "No central logging",
        points: 0,
      },
    ],
  },
  {
    f: "detect",
    text: "What protects and watches your endpoints and servers?",
    help: "",
    options: [
      {
        label: "EDR/MDR on every endpoint and server, monitored 24/7",
        points: 3,
      },
      {
        label: "EDR deployed, monitored business hours",
        points: 2,
      },
      {
        label: "Traditional antivirus only",
        points: 1,
      },
      {
        label: "Inconsistent coverage",
        points: 0,
      },
    ],
  },
  {
    f: "detect",
    text: "How would you know if an attacker were inside your environment right now?",
    help: "",
    options: [
      {
        label: "Tested detections for lateral movement, privilege abuse, and data exfiltration",
        points: 3,
      },
      {
        label: "Alerts on known malware",
        points: 2,
      },
      {
        label: "A user would report something odd",
        points: 1,
      },
      {
        label: "We would not know",
        points: 0,
      },
    ],
  },
  {
    f: "detect",
    text: "Is activity in your cloud and SaaS platforms (M365 / Google Workspace, admin consoles) monitored?",
    help: "",
    options: [
      {
        label: "Monitored with alerts on risky sign-ins and configuration changes",
        points: 3,
      },
      {
        label: "Some logs reviewed periodically",
        points: 2,
      },
      {
        label: "Default settings only",
        points: 1,
      },
      {
        label: "Not monitored",
        points: 0,
      },
    ],
  },
  {
    f: "respond",
    text: "Do you have a written incident response plan — and has it been tested?",
    help: "",
    options: [
      {
        label: "Tested in a tabletop within 12 months; roles and contacts named",
        points: 3,
      },
      {
        label: "Written, never tested",
        points: 2,
      },
      {
        label: "Draft or informal",
        points: 1,
      },
      {
        label: "None",
        points: 0,
      },
    ],
  },
  {
    f: "respond",
    text: "Do you know your breach-notification obligations under {FW}, and have a process to meet them?",
    help: "",
    options: [
      {
        label: "Documented timelines, counsel engaged, notification templates ready",
        points: 3,
      },
      {
        label: "We know them roughly",
        points: 2,
      },
      {
        label: "We would look them up during an incident",
        points: 1,
      },
      {
        label: "Unaware",
        points: 0,
      },
    ],
  },
  {
    f: "respond",
    text: "Who would you call in the first hour of a serious incident?",
    help: "",
    options: [
      {
        label: "Retained IR/forensics partner named in the plan and approved by our insurer",
        points: 3,
      },
      {
        label: "We know who we would call",
        points: 2,
      },
      {
        label: "We would search for help",
        points: 1,
      },
      {
        label: "No one identified",
        points: 0,
      },
    ],
  },
  {
    f: "respond",
    text: "Cyber insurance — do you meet the requirements on your application, with evidence?",
    help: "",
    options: [
      {
        label: "Requirements mapped to controls, evidence ready",
        points: 3,
      },
      {
        label: "Insured, mostly compliant",
        points: 2,
      },
      {
        label: "Insured, haven't checked",
        points: 1,
      },
      {
        label: "No coverage, or not sure",
        points: 0,
      },
    ],
  },
  {
    f: "recover",
    text: "Could you restore from backups after ransomware?",
    help: "",
    options: [
      {
        label: "Immutable and offline copies; restores tested quarterly; RTO/RPO documented",
        points: 3,
      },
      {
        label: "Restores tested annually",
        points: 2,
      },
      {
        label: "Backups exist; restores rarely tested",
        points: 1,
      },
      {
        label: "Not confident",
        points: 0,
      },
    ],
  },
  {
    f: "recover",
    text: "Is there a business continuity plan for a multi-day outage of {SYSTEMS}?",
    help: "",
    options: [
      {
        label: "Documented and exercised; critical processes prioritized",
        points: 3,
      },
      {
        label: "Documented, never exercised",
        points: 2,
      },
      {
        label: "Informal",
        points: 1,
      },
      {
        label: "None",
        points: 0,
      },
    ],
  },
  {
    f: "recover",
    text: "After an incident or near miss, what happens?",
    help: "",
    options: [
      {
        label: "Formal review; root cause feeds the risk register and control changes",
        points: 3,
      },
      {
        label: "Informal debrief",
        points: 2,
      },
      {
        label: "Fix it and move on",
        points: 1,
      },
      {
        label: "Nothing",
        points: 0,
      },
    ],
  },
  {
    f: "recover",
    text: "Could you prove all of this to {AUD} this month?",
    help: "Policies, logs, access reviews, training records, test results.",
    options: [
      {
        label: "Yes — evidence organized in a GRC platform",
        points: 3,
      },
      {
        label: "Yes, scattered across tools and inboxes",
        points: 2,
      },
      {
        label: "Some, with significant effort",
        points: 1,
      },
      {
        label: "No",
        points: 0,
      },
    ],
  },
];

/** The seven verticals a brand can be pointed at. */
export const VERTICALS: Record<string, Vertical> = {
  cmmc: {
    id: "cmmc",
    label: "Defense / CMMC",
    audience: "defense contractors and subcontractors",
    framework: "CMMC Level 2 / NIST SP 800-171",
    data: "Controlled Unclassified Information (CUI)",
    systems: "your CUI environment",
    auditor: "a C3PAO assessor or your prime contractor",
    headline: "Your contracts now depend on a certification you do not hold yet.",
    subhead: "CMMC Level 2 is a condition of award, and primes are asking subcontractors for proof today. Find out how ready you are in seven minutes — then get the playbook that sequences the work.",
    problemHead: "The DoD supply chain is being sorted into contractors who can prove it and contractors who cannot.",
    problemBody: "NIST SP 800-171 has 110 controls. Most contractors have implemented some, documented few, and can evidence fewer. Assessors do not grade on intent.",
    pressures: [
      {
        who: "Your prime contractor",
        ask: "Send us your SPRS score and your CMMC status.",
        why: "Flow-down clauses make your readiness their problem — and they will pick the subcontractor who can answer.",
      },
      {
        who: "The assessor",
        ask: "Show me the evidence for each control.",
        why: "A System Security Plan and POA&M are the minimum. Evidence for every practice is what passes.",
      },
      {
        who: "Your leadership",
        ask: "What happens to revenue if we are not certified in time?",
        why: "Certification timelines run months. Waiting for the solicitation to require it is too late.",
      },
    ],
    stakesHead: "Lose eligibility and you lose the contract — no appeal.",
    stakes: [
      "A recompete requires CMMC Level 2 and you are not ready for the assessment",
      "Your prime replaces you with a certified subcontractor to protect their own award",
      "An inaccurate SPRS self-attestation becomes a False Claims Act exposure",
      "CUI spills across an unscoped environment and the incident is reportable to DoD",
    ],
    deadlineLabel: "Contract or assessment deadline",
    sensitiveLabel: "We handle CUI or FCI",
    playbook: "The CMMC Level 2 Readiness Playbook",
    guideProof: "Cyber AB Registered Practitioner Organization; CMMC readiness through C3PAO prep; Microsoft GCC High enclave design",
    readiness: "CMMC Readiness, Remediation, Management & Auditing (+ GCC High Certified Enclave)",
  },
  hipaa: {
    id: "hipaa",
    label: "Healthcare / HIPAA",
    audience: "healthcare organizations and business associates",
    framework: "the HIPAA Security Rule",
    data: "protected health information (PHI)",
    systems: "your EHR and clinical systems",
    auditor: "OCR or a covered-entity partner",
    headline: "Ransomware in a clinical setting is not an IT problem. It is a patient-safety problem.",
    subhead: "HIPAA requires a documented, current security risk assessment — and your partners are asking for proof of one. See where you stand in seven minutes and get the playbook that closes the gaps.",
    problemHead: "Healthcare is the most-attacked sector, and the Security Rule assumes you already know your risks.",
    problemBody: "Most organizations have a privacy officer and a policy binder. Fewer have a current risk analysis, tested backups, and evidence that safeguards actually operate.",
    pressures: [
      {
        who: "Covered entities & partners",
        ask: "Sign the BAA — and show us your risk assessment.",
        why: "Partners are pushing accountability down the chain. A missing risk analysis ends the conversation.",
      },
      {
        who: "OCR",
        ask: "Where is your risk analysis and risk management plan?",
        why: "It is the most-cited failure in enforcement actions, and settlements follow.",
      },
      {
        who: "Your board & insurer",
        ask: "Could we keep treating patients through an outage?",
        why: "Downtime procedures and recovery are now underwriting questions.",
      },
    ],
    stakesHead: "A breach here costs more than money.",
    stakes: [
      "Clinical downtime while systems are rebuilt from backups nobody tested",
      "OCR investigation finds no current risk analysis — the most common finding",
      "A partner terminates the BAA over an unanswered security questionnaire",
      "Patient notification letters, credit monitoring, and the headline that follows",
    ],
    deadlineLabel: "Next risk assessment, audit, or partner deadline",
    sensitiveLabel: "We create, store, or transmit PHI",
    playbook: "The HIPAA Security Risk Assessment Playbook",
    guideProof: "HITRUST-certified firm; annual HIPAA Security Risk Assessments and healthcare compliance programs",
    readiness: "HIPAA Security Risk Assessment & Healthcare Compliance Program",
  },
  soc2: {
    id: "soc2",
    label: "SaaS & Technology / SOC 2",
    audience: "SaaS and technology companies",
    framework: "SOC 2 Type II",
    data: "customer data",
    systems: "your production platform",
    auditor: "your enterprise customers and their auditors",
    headline: "Every enterprise deal now ends with the same question: where is your SOC 2?",
    subhead: "Security questionnaires stall your pipeline and a missing report loses the deal. See how close you are to audit-ready in seven minutes — and get the playbook that gets you there.",
    problemHead: "You sell trust. Buyers now want it audited.",
    problemBody: "Procurement teams treat a SOC 2 Type II as table stakes. Without it, every deal becomes a custom security review your engineers have to staff.",
    pressures: [
      {
        who: "Enterprise buyers",
        ask: "Send your SOC 2 report or complete this 300-question review.",
        why: "Deals slip a quarter while engineers answer questionnaires from memory.",
      },
      {
        who: "Your auditor",
        ask: "Show operating evidence across the observation period.",
        why: "Type II means proving controls ran for months, not that they exist today.",
      },
      {
        who: "Your investors",
        ask: "What is our exposure if a customer is breached through us?",
        why: "Security posture is now diligence — for the round and for the exit.",
      },
    ],
    stakesHead: "Every quarter without a report is a quarter of deals that stall.",
    stakes: [
      "A flagship prospect chooses the competitor with a report on file",
      "A customer breach through your platform triggers contractual penalties",
      "Engineering loses weeks to bespoke questionnaires instead of shipping",
      "Your observation period cannot start until controls are actually in place",
    ],
    deadlineLabel: "Customer deadline for a SOC 2 report",
    sensitiveLabel: "We process customer data in production",
    playbook: "The SOC 2 Type II Readiness Playbook",
    guideProof: "SOC 2 Type II holders ourselves; readiness through audit with 100% client audit success",
    readiness: "SOC 2 Readiness, Remediation, Management & Auditing",
  },
  finance: {
    id: "finance",
    label: "Financial services",
    audience: "banks, credit unions, and financial firms",
    framework: "GLBA, FFIEC, and state regulator expectations",
    data: "customer financial data",
    systems: "your core and payment systems",
    auditor: "your examiners and cyber insurer",
    headline: "Examiners, insurers, and attackers are all reading your controls. Are you?",
    subhead: "Financial firms are among the most-targeted organizations anywhere, and the regulatory bar rises every cycle. See where your program stands in seven minutes and get the playbook that closes the gaps.",
    problemHead: "The exam is not the risk. The exam is where the risk becomes visible.",
    problemBody: "Regulators expect a documented, risk-based program with board oversight. Insurers expect the controls on the application to actually exist. Attackers expect neither.",
    pressures: [
      {
        who: "Examiners",
        ask: "Show us board oversight, risk assessment, and vendor management.",
        why: "Findings become matters requiring attention — and follow you into the next cycle.",
      },
      {
        who: "Your cyber insurer",
        ask: "Confirm MFA, EDR, immutable backups, and tested response.",
        why: "Misstatements are grounds to deny a claim when you need it most.",
      },
      {
        who: "Your customers",
        ask: "Is my money — and my data — safe with you?",
        why: "One incident, one disclosure, and trust built over decades erodes.",
      },
    ],
    stakesHead: "Findings compound. So does exposure.",
    stakes: [
      "An exam finding on information security that recurs next cycle",
      "A denied cyber claim because a control on the application was not in place",
      "Business-email compromise redirecting a wire your controls should have caught",
      "A vendor breach that becomes your notification obligation",
    ],
    deadlineLabel: "Next exam or audit date",
    sensitiveLabel: "We hold customer financial or account data",
    playbook: "The Financial Services Security Program Playbook",
    guideProof: "Penetration testing, risk assessments, and examiner-ready governance programs for banks and credit unions",
    readiness: "Risk Assessment + vCISO Services (examiner-ready program)",
  },
  legal: {
    id: "legal",
    label: "Legal",
    audience: "law firms and legal service providers",
    framework: "client security requirements and ABA guidance",
    data: "privileged client information",
    systems: "your document and practice management systems",
    auditor: "your clients' outside-counsel guideline reviews",
    headline: "Your clients trust you with privilege. Their security questionnaires are asking whether they should.",
    subhead: "Firms hold client funds, privileged communications, and case strategy — and corporate clients now audit their outside counsel. See where you stand in seven minutes and get the playbook that answers them.",
    problemHead: "Confidentiality is an ethical duty. Proving it is now a business requirement.",
    problemBody: "Outside-counsel guidelines increasingly require MFA, encryption, incident response plans, and independent assessments. Firms that cannot evidence them are quietly removed from panels.",
    pressures: [
      {
        who: "Corporate clients",
        ask: "Complete our outside-counsel security requirements.",
        why: "Panel status depends on the answers — and on evidence, not assurances.",
      },
      {
        who: "Your malpractice & cyber insurers",
        ask: "Which controls are actually in place?",
        why: "Premiums and coverage now depend on MFA, backups, and tested response.",
      },
      {
        who: "Your partners",
        ask: "What is our exposure if a matter is compromised?",
        why: "A breach of privileged material is a client crisis and a bar issue at once.",
      },
    ],
    stakesHead: "Panel removal happens quietly. Breaches do not.",
    stakes: [
      "A key client drops the firm from its panel after a failed security review",
      "Wire-fraud loss of client funds through business-email compromise",
      "Ransomware locking case files days before a filing deadline",
      "A privileged-data breach that becomes a public disclosure and a bar complaint",
    ],
    deadlineLabel: "Client security review or renewal date",
    sensitiveLabel: "We hold privileged client data or client funds",
    playbook: "The Law Firm Security & Client Assurance Playbook",
    guideProof: "Security programs built around client confidentiality, outside-counsel requirements, and ransomware resilience",
    readiness: "Security Maturity Level Assessment + vCISO Services",
  },
  manufacturing: {
    id: "manufacturing",
    label: "Manufacturing",
    audience: "manufacturers and industrial companies",
    framework: "NIST CSF and customer flow-down requirements",
    data: "production systems and customer intellectual property",
    systems: "your production and ERP systems",
    auditor: "your customers' supplier security reviews",
    headline: "One ransomware event stops the line. Your customers know it — and they are asking.",
    subhead: "Manufacturing is now the most-targeted sector for ransomware, and large customers push security requirements down their supply chain. See where you stand in seven minutes and get the playbook that keeps the line running.",
    problemHead: "Uptime was always the priority. Now uptime depends on security.",
    problemBody: "Flat networks, aging OT, and remote vendor access make plants easy targets. Customers are responding with supplier security reviews you have to pass to keep the order.",
    pressures: [
      {
        who: "Your customers",
        ask: "Complete our supplier cybersecurity assessment.",
        why: "Preferred-supplier status now includes security posture — and flow-down clauses make it contractual.",
      },
      {
        who: "Your insurer",
        ask: "How segmented is OT from IT? How fast can you restore?",
        why: "Business-interruption coverage depends on the answers.",
      },
      {
        who: "Your plant leadership",
        ask: "How long would we be down?",
        why: "Most manufacturers hit by ransomware lose more than a week of production.",
      },
    ],
    stakesHead: "Downtime is the cost everyone understands.",
    stakes: [
      "Days of lost production while systems are rebuilt",
      "A customer suspends orders pending a security review you cannot pass",
      "Theft of designs and pricing that surfaces at a competitor",
      "A vendor remote-access account becomes the entry point to the plant floor",
    ],
    deadlineLabel: "Customer review or contract deadline",
    sensitiveLabel: "We hold customer IP or handle CUI for defense customers",
    playbook: "The Manufacturing Cyber Resilience Playbook",
    guideProof: "Ransomware recovery case work with US manufacturers; CIS Benchmark Hardening; DFARS/CMMC for defense suppliers",
    readiness: "Security Maturity Level Assessment + CIS Benchmark Hardening",
  },
  nonprofit: {
    id: "nonprofit",
    label: "Not-for-profit",
    audience: "nonprofits and mission-driven organizations",
    framework: "donor-data protection and grant compliance requirements",
    data: "donor, member, and beneficiary data",
    systems: "your donor and program systems",
    auditor: "your board, funders, and auditors",
    headline: "Your mission runs on trust. Donor data is where that trust is tested.",
    subhead: "Nonprofits hold payment data, personal information about vulnerable people, and grant obligations — with a fraction of the security staff. See where you stand in seven minutes and get a playbook sized for your organization.",
    problemHead: "Attackers know nonprofits are under-resourced. So do your funders.",
    problemBody: "Grant agreements and payment processors increasingly require documented security controls. The gap between what is promised and what is in place is where organizations get hurt.",
    pressures: [
      {
        who: "Funders & grantors",
        ask: "Confirm your data-protection controls as a condition of the grant.",
        why: "Compliance clauses in grant agreements are audited — and revocable.",
      },
      {
        who: "Your board",
        ask: "What is our exposure, and what are we doing about it?",
        why: "Fiduciary duty now includes cyber oversight.",
      },
      {
        who: "Your donors & beneficiaries",
        ask: "Is my information safe with you?",
        why: "A breach of vulnerable people's data is a mission failure, not just a technical one.",
      },
    ],
    stakesHead: "The cost of a breach is measured in trust you cannot rebuild quickly.",
    stakes: [
      "Business-email compromise redirecting a major gift or grant payment",
      "A grant clawback after a compliance audit finds missing controls",
      "Exposure of beneficiary data that puts vulnerable people at risk",
      "Weeks of program disruption with no recovery plan",
    ],
    deadlineLabel: "Grant, audit, or board deadline",
    sensitiveLabel: "We store donor payment data or sensitive beneficiary information",
    playbook: "The Nonprofit Security Essentials Playbook",
    guideProof: "Right-sized programs, policy workshops, and vCISO leadership for resource-constrained organizations",
    readiness: "Risk Assessment + Cybersecurity Policy Workshops",
  },
};

/** Recommendation copy per CSF function per status. */
export const RECS: RecTable = {
  govern: {
    gap: [
      "Put someone accountable for security",
      "Without a named owner there is no program — only tasks. Establish executive ownership (a CISO or vCISO), approve a policy set aligned to {FW}, and stand up a risk register leadership actually reviews.",
      "vCISO Services + Cybersecurity Policy Workshops",
    ],
    watch: [
      "Formalize the governance rhythm",
      "Ownership exists; cadence does not. Institute quarterly leadership risk reviews, annual policy attestation, and vendor reviews on a schedule.",
      "vCISO Services",
    ],
    strong: [
      "Governance is working",
      "Keep the cadence and record it — board minutes and review logs are exactly what {AUD} asks for first.",
      "Managed Compliance (Manage phase)",
    ],
  },
  identify: {
    gap: [
      "Find out what you have and where {DATA} lives",
      "You cannot protect what you cannot see. Build asset and data inventories, map data flows, and run an independent risk assessment against {FW}.",
      "Risk Assessment + Vulnerability Assessment",
    ],
    watch: [
      "Close inventory and scanning gaps",
      "Move to continuous vulnerability scanning with remediation SLAs and keep the data inventory current as systems change.",
      "Vulnerability Assessments + Risk Assessment",
    ],
    strong: [
      "Visibility is solid",
      "Refresh the risk assessment annually and after major changes; it anchors everything else.",
      "Annual Risk Assessment (Manage phase)",
    ],
  },
  protect: {
    gap: [
      "Harden the fundamentals",
      "MFA everywhere, least-privilege access to {DATA}, encryption on every device, and trained people close most of the attack surface — and are the first things {AUD} checks.",
      "CIS Benchmark Hardening + Security Awareness Program",
    ],
    watch: [
      "Extend protection to the edges",
      "Cover remaining systems with MFA, run quarterly access reviews, and add phishing simulation with tracked results.",
      "CIS Benchmark Hardening",
    ],
    strong: [
      "Protective controls are mature",
      "Maintain them with configuration baselines and periodic access recertification.",
      "Managed Cybersecurity (Manage phase)",
    ],
  },
  detect: {
    gap: [
      "Get eyes on your environment",
      "Without central logging and 24/7 monitoring an intruder has weeks, not minutes. Deploy EDR on every endpoint and route logs to a monitored SOC.",
      "SOC-as-a-Service + EDR/MDR deployment",
    ],
    watch: [
      "Tune and extend detection",
      "Move from business-hours review to 24/7 alerting, add cloud/SaaS admin monitoring, and test detections against real attacker behavior.",
      "SOC-as-a-Service + Penetration Testing",
    ],
    strong: [
      "Detection is a strength",
      "Validate it annually with a penetration test and keep detections tuned to your environment.",
      "Penetration Testing (annual)",
    ],
  },
  respond: {
    gap: [
      "Prepare to respond before you must",
      "Write and tabletop an incident response plan, document {FW} notification timelines, and retain an IR and forensics partner your insurer accepts.",
      "Incident Response Planning + 24/7 IR & Recovery",
    ],
    watch: [
      "Test the plan",
      "Run a tabletop this quarter, name the first-hour contacts, and map cyber-insurance requirements to evidence.",
      "Incident Response Planning",
    ],
    strong: [
      "Response readiness is documented",
      "Exercise annually and after significant changes; keep the retainer current.",
      "24/7 IR & Recovery retainer",
    ],
  },
  recover: {
    gap: [
      "Make sure you can come back",
      "Immutable backups with tested restores and an exercised continuity plan are the difference between a bad week and a closed business — and the evidence to prove it is what {AUD} wants to see.",
      "Cyber Recovery Planning + GRC platform onboarding",
    ],
    watch: [
      "Prove recovery works",
      "Test restores quarterly, exercise the continuity plan, and centralize evidence so proof takes hours, not weeks.",
      "Cyber Recovery Planning + GRC platform",
    ],
    strong: [
      "Recovery and proof are in place",
      "Keep the test cadence and use the evidence pack proactively with customers, insurers, and auditors.",
      "Managed Compliance (Manage phase)",
    ],
  },
};

/** Readiness tiers by minimum score. */
export const TIERS: Tier[] = [
  {
    n: 1,
    name: "Exposed",
    min: 0,
    summary: "Security depends on individual effort, not a program.",
    detail: "Few controls are documented, tested, or provable. A serious incident or a formal review would expose the gaps quickly — but the highest-impact fixes are also the most straightforward.",
  },
  {
    n: 2,
    name: "Developing",
    min: 40,
    summary: "Controls exist; coverage and evidence are inconsistent.",
    detail: "You have the beginnings of a program. The gaps are in consistency, testing, and the ability to prove controls operate — which is exactly what {AUD} will probe.",
  },
  {
    n: 3,
    name: "Established",
    min: 60,
    summary: "A defined program exists and mostly operates.",
    detail: "Policies, controls, and monitoring are largely in place. Closing the remaining gaps and organizing evidence would make the program defensible against {FW}.",
  },
  {
    n: 4,
    name: "Resilient",
    min: 80,
    summary: "Documented, tested, and provable on request.",
    detail: "Your program operates at the level {AUD} expects. The work now is sustaining it — and using it as a competitive advantage.",
  },
];

/** Shipped defaults for the lead qualification rule; admin-editable. */
export const DEFAULT_QUAL: Qualification = {
  hotScoreBelow: 60,
  hotDays: 90,
  warmScoreBelow: 75,
  warmDays: 180,
};

/** Framework chips offered on the lead gate. */
export const FW_CHIPS: string[] = [
  "CMMC",
  "NIST 800-171",
  "HIPAA",
  "SOC 2",
  "ISO 27001",
  "PCI DSS",
  "GLBA / FFIEC",
  "State privacy law",
  "None yet",
];

export const CLIENT_ASSESSMENT_VERSION = 'client-1.0';
