// AUTO-GENERATED by tools/extract-data.mjs — do not edit by hand.
// Source of truth: reference/msp-logic.js
// Regenerate with `npm run generate:data`.

import type { Domain, MspQuestion, RecTable, LevelText, Scoring } from '@/lib/types';

/** Six assessment domains, in presentation order. */
export const DOMAINS: Domain[] = [
  {
    id: "tooling",
    name: "Tooling & Stack Maturity",
    blurb: "MFA, privileged access, EDR, RMM hardening",
  },
  {
    id: "lifecycle",
    name: "Client Onboarding & Offboarding",
    blurb: "Baselines, access removal, contract clarity",
  },
  {
    id: "ir",
    name: "Incident Response Readiness",
    blurb: "Plans, partners, backups, insurance",
  },
  {
    id: "compliance",
    name: "Compliance Obligations",
    blurb: "CMMC, HIPAA, SOC 2 — for clients and for you",
  },
  {
    id: "vendor",
    name: "Vendor & Supply-Chain Risk",
    blurb: "Your stack, your subcontractors, your inventory",
  },
  {
    id: "proof",
    name: "Proof & Evidence",
    blurb: "What happens when a client asks you to prove it",
  },
];

/** 24 questions; option order is best → worst and points are `3 - index`. */
export const QUESTIONS: MspQuestion[] = [
  {
    d: "tooling",
    text: "How is MFA enforced for your own staff on admin tools — RMM, PSA, M365/Google admin, documentation?",
    help: "Answer for how it works today, not policy.",
    options: [
      {
        label: "Enforced everywhere; phishing-resistant (FIDO2/passkeys) for admin roles",
        points: 3,
      },
      {
        label: "Enforced on most tools; SMS or app-based",
        points: 2,
      },
      {
        label: "Enabled but optional or inconsistent by tool",
        points: 1,
      },
      {
        label: "Not enforced, or not sure",
        points: 0,
      },
    ],
  },
  {
    d: "tooling",
    text: "How do your technicians access privileged accounts in client environments?",
    help: "Think domain admin, M365 global admin, firewall logins.",
    options: [
      {
        label: "Per-tech accounts, PAM/vault with just-in-time elevation, sessions logged",
        points: 3,
      },
      {
        label: "Per-tech accounts in a shared vault, reviewed periodically",
        points: 2,
      },
      {
        label: "Shared credentials in a password manager",
        points: 1,
      },
      {
        label: "Shared credentials in spreadsheets, docs, or memory",
        points: 0,
      },
    ],
  },
  {
    d: "tooling",
    text: "What endpoint protection covers your own MSP systems and your clients?",
    help: "",
    options: [
      {
        label: "EDR/MDR on everything, monitored 24/7",
        points: 3,
      },
      {
        label: "EDR deployed, monitored during business hours",
        points: 2,
      },
      {
        label: "Traditional antivirus only",
        points: 1,
      },
      {
        label: "Inconsistent — coverage unknown on some endpoints",
        points: 0,
      },
    ],
  },
  {
    d: "tooling",
    text: "How is your RMM and remote-access tooling hardened?",
    help: "RMM compromise is the most common path into MSP client bases.",
    options: [
      {
        label: "Hardened to vendor/CIS baseline, IP-restricted, patched within days, reviewed quarterly",
        points: 3,
      },
      {
        label: "Patched promptly, MFA on, default config otherwise",
        points: 2,
      },
      {
        label: "Default configuration, patched eventually",
        points: 1,
      },
      {
        label: "Not sure how it's configured",
        points: 0,
      },
    ],
  },
  {
    d: "lifecycle",
    text: "When you onboard a new client, is there a documented security baseline you apply?",
    help: "",
    options: [
      {
        label: "Documented baseline mapped to CIS/NIST, signed off by the client",
        points: 3,
      },
      {
        label: "Documented internal checklist",
        points: 2,
      },
      {
        label: "Informal — varies by technician",
        points: 1,
      },
      {
        label: "No baseline",
        points: 0,
      },
    ],
  },
  {
    d: "lifecycle",
    text: "When a client leaves, how are your agents, credentials, and access removed?",
    help: "",
    options: [
      {
        label: "Same day, checklist-driven, verified and documented",
        points: 3,
      },
      {
        label: "Within a week, using a checklist",
        points: 2,
      },
      {
        label: "Eventually, ad hoc",
        points: 1,
      },
      {
        label: "We don't have a process",
        points: 0,
      },
    ],
  },
  {
    d: "lifecycle",
    text: "When a technician leaves your MSP, how quickly is their access to every client environment revoked?",
    help: "",
    options: [
      {
        label: "Same day — central identity, automated, verified",
        points: 3,
      },
      {
        label: "Within 24–48 hours via manual checklist",
        points: 2,
      },
      {
        label: "Within a week or two",
        points: 1,
      },
      {
        label: "Uncertain — depends who remembers",
        points: 0,
      },
    ],
  },
  {
    d: "lifecycle",
    text: "Do your client agreements define who owns which security responsibilities?",
    help: "Yours vs. theirs vs. a third party.",
    options: [
      {
        label: "Yes — responsibility matrix reviewed by counsel, in every MSA",
        points: 3,
      },
      {
        label: "Yes, in most contracts",
        points: 2,
      },
      {
        label: "Vague language only",
        points: 1,
      },
      {
        label: "No",
        points: 0,
      },
    ],
  },
  {
    d: "ir",
    text: "Do you have a written incident response plan for your own MSP — not just for clients?",
    help: "",
    options: [
      {
        label: "Yes, tabletop-tested in the last 12 months",
        points: 3,
      },
      {
        label: "Yes, but never tested",
        points: 2,
      },
      {
        label: "Draft or informal",
        points: 1,
      },
      {
        label: "No",
        points: 0,
      },
    ],
  },
  {
    d: "ir",
    text: "A client is hit with ransomware tonight. Who leads?",
    help: "",
    options: [
      {
        label: "Named IR lead, retained IR/forensics partner, call tree ready",
        points: 3,
      },
      {
        label: "Internal lead, no external partner on retainer",
        points: 2,
      },
      {
        label: "We'd figure it out quickly",
        points: 1,
      },
      {
        label: "Not sure",
        points: 0,
      },
    ],
  },
  {
    d: "ir",
    text: "How confident are you in restoring from backups — for clients and for your own systems?",
    help: "",
    options: [
      {
        label: "Immutable/offline copies, restores tested quarterly, RTO/RPO documented",
        points: 3,
      },
      {
        label: "Restores tested annually",
        points: 2,
      },
      {
        label: "Backups exist; restores rarely tested",
        points: 1,
      },
      {
        label: "Not confident",
        points: 0,
      },
    ],
  },
  {
    d: "ir",
    text: "Do you know what your cyber insurance policy requires of you — and do you meet it?",
    help: "",
    options: [
      {
        label: "Yes — requirements mapped to controls, evidence ready",
        points: 3,
      },
      {
        label: "Insured, mostly compliant",
        points: 2,
      },
      {
        label: "Insured, haven't checked the requirements",
        points: 1,
      },
      {
        label: "No coverage, or not sure",
        points: 0,
      },
    ],
  },
  {
    d: "compliance",
    text: "When clients face CMMC, HIPAA, SOC 2, or PCI, how prepared are you to support them?",
    help: "",
    options: [
      {
        label: "Documented support for multiple frameworks, with a partner for governance",
        points: 3,
      },
      {
        label: "Documented support for one or two frameworks",
        points: 2,
      },
      {
        label: "We handle it case by case",
        points: 1,
      },
      {
        label: "Haven't been asked yet, or not sure",
        points: 0,
      },
    ],
  },
  {
    d: "compliance",
    text: "Does your MSP hold its own third-party attestation (SOC 2, ISO 27001, CMMC)?",
    help: "",
    options: [
      {
        label: "Yes, current",
        points: 3,
      },
      {
        label: "In progress",
        points: 2,
      },
      {
        label: "Planned within 12 months",
        points: 1,
      },
      {
        label: "No",
        points: 0,
      },
    ],
  },
  {
    d: "compliance",
    text: "Are your own policies — access control, acceptable use, change management, vendor management — written, approved, and reviewed annually?",
    help: "",
    options: [
      {
        label: "Complete set, reviewed annually, staff attest",
        points: 3,
      },
      {
        label: "Most written; review is irregular",
        points: 2,
      },
      {
        label: "A few documents",
        points: 1,
      },
      {
        label: "None",
        points: 0,
      },
    ],
  },
  {
    d: "compliance",
    text: "BAAs, DFARS flow-down clauses, or similar you have signed with clients — do you know what they commit you to?",
    help: "",
    options: [
      {
        label: "Yes — tracked in a register with mapped controls",
        points: 3,
      },
      {
        label: "Signed and loosely tracked",
        points: 2,
      },
      {
        label: "Signed some; not tracked",
        points: 1,
      },
      {
        label: "Not sure what we've signed",
        points: 0,
      },
    ],
  },
  {
    d: "vendor",
    text: "Do you assess the security of your own critical vendors — RMM, PSA, backup, EDR, documentation?",
    help: "",
    options: [
      {
        label: "Formal annual review, SOC reports collected, vendor register maintained",
        points: 3,
      },
      {
        label: "Reviewed at onboarding only",
        points: 2,
      },
      {
        label: "We rely on vendor reputation",
        points: 1,
      },
      {
        label: "No",
        points: 0,
      },
    ],
  },
  {
    d: "vendor",
    text: "How do you learn about vendor breaches or critical CVEs in your stack?",
    help: "",
    options: [
      {
        label: "Subscribed advisories plus a defined response SLA",
        points: 3,
      },
      {
        label: "We monitor advisories; response is ad hoc",
        points: 2,
      },
      {
        label: "News and social media",
        points: 1,
      },
      {
        label: "Usually after the fact",
        points: 0,
      },
    ],
  },
  {
    d: "vendor",
    text: "Do you maintain a current hardware/software/SaaS inventory for your MSP and each client?",
    help: "",
    options: [
      {
        label: "Automated, current, includes SaaS",
        points: 3,
      },
      {
        label: "Maintained, mostly current",
        points: 2,
      },
      {
        label: "Partial",
        points: 1,
      },
      {
        label: "No",
        points: 0,
      },
    ],
  },
  {
    d: "vendor",
    text: "Subcontractors or third parties that touch client environments (NOC, help desk, project work) — how are they controlled?",
    help: "",
    options: [
      {
        label: "Vetted, contractually bound, access monitored",
        points: 3,
      },
      {
        label: "Contracts in place, limited monitoring",
        points: 2,
      },
      {
        label: "Informal arrangements",
        points: 1,
      },
      {
        label: "We don't track this",
        points: 0,
      },
    ],
  },
  {
    d: "proof",
    text: "A client or prospect sends a security questionnaire. What happens?",
    help: "",
    options: [
      {
        label: "Standard answer library plus evidence pack — turned around in days",
        points: 3,
      },
      {
        label: "We answer from memory; usually accurate",
        points: 2,
      },
      {
        label: "We scramble each time",
        points: 1,
      },
      {
        label: "We avoid or delay them",
        points: 0,
      },
    ],
  },
  {
    d: "proof",
    text: "Could you produce evidence today — logs, policies, access reviews — for a client's auditor?",
    help: "",
    options: [
      {
        label: "Yes, organized in a GRC platform",
        points: 3,
      },
      {
        label: "Yes, scattered across tools",
        points: 2,
      },
      {
        label: "Some, with effort",
        points: 1,
      },
      {
        label: "No",
        points: 0,
      },
    ],
  },
  {
    d: "proof",
    text: "How often do you review who has access to what across client environments?",
    help: "",
    options: [
      {
        label: "Quarterly, documented, exceptions remediated",
        points: 3,
      },
      {
        label: "Annually",
        points: 2,
      },
      {
        label: "When something prompts it",
        points: 1,
      },
      {
        label: "Never",
        points: 0,
      },
    ],
  },
  {
    d: "proof",
    text: "Has an independent third party assessed your MSP's security in the last 12 months?",
    help: "Pen test, risk assessment, or maturity assessment.",
    options: [
      {
        label: "Yes — findings remediated",
        points: 3,
      },
      {
        label: "Yes — findings partially addressed",
        points: 2,
      },
      {
        label: "More than a year ago",
        points: 1,
      },
      {
        label: "Never",
        points: 0,
      },
    ],
  },
];

/** Recommendation copy per domain per status. */
export const RECS: RecTable = {
  tooling: {
    gap: [
      "Harden the tools that hold the keys",
      "Your RMM, PSA, and admin identities are the highest-value targets in your practice. Enforce phishing-resistant MFA for admin roles, move privileged access into a vault with per-tech accounts, and baseline your RMM to CIS.",
      "CIS Benchmark Hardening + Security Maturity Level Assessment",
    ],
    watch: [
      "Close the gaps in privileged access",
      "Coverage is uneven. Standardize EDR across every endpoint and formalize a quarterly configuration review of your RMM and remote-access tooling.",
      "CIS Benchmark Hardening",
    ],
    strong: [
      "Keep your stack hardened",
      "Your tooling controls are mature. Fold them into a managed program so configuration drift and new tools don't erode them.",
      "Managed Cybersecurity (Manage phase)",
    ],
  },
  lifecycle: {
    gap: [
      "Build a client lifecycle baseline",
      "Onboarding and offboarding are where access lingers and liability accrues. Create a documented security baseline, a same-day offboarding checklist for clients and technicians, and a responsibility matrix in your MSA.",
      "MSP Cyber Consulting & Training",
    ],
    watch: [
      "Formalize responsibilities in your contracts",
      "Your process exists but your paper may not protect you. Add a reviewed responsibility matrix to every agreement and verify access removal rather than assuming it.",
      "MSP Cyber Consulting & Training + Cybersecurity Policy Workshop",
    ],
    strong: [
      "Lifecycle controls are defensible",
      "Keep the evidence: retain completed offboarding checklists and access-removal verification per client.",
      "Managed Cybersecurity (Manage phase)",
    ],
  },
  ir: {
    gap: [
      "Get incident-ready before the call comes",
      "Without a tested plan, a named lead, and verified restores, a client incident becomes your incident. Write and tabletop an IR plan for the MSP itself, retain an IR partner, and test immutable restores quarterly.",
      "Incident Response Planning + 24/7 IR & Recovery",
    ],
    watch: [
      "Test what you have",
      "A plan that has never been exercised is a hypothesis. Run a tabletop this quarter, test restores, and map your cyber-insurance requirements to real controls.",
      "Incident Response Planning",
    ],
    strong: [
      "Response readiness is a selling point",
      "Document it for clients and insurers. You can answer 'who leads' with a name — most MSPs cannot.",
      "Managed Cybersecurity (Manage phase)",
    ],
  },
  compliance: {
    gap: [
      "Get out of the compliance gray zone",
      "Clients in regulated industries will hold you inside their boundary whether or not you are ready. Establish a policy set, track what you have signed, and start toward your own attestation with CISO-level ownership.",
      "vCISO Services + SOC 2 / ISO 27001 / CMMC Readiness",
    ],
    watch: [
      "Turn effort into attestation",
      "You are doing much of the work without the credential. A readiness engagement converts existing controls into audit-ready evidence and a certificate you can put in front of prospects.",
      "SOC 2 / ISO 27001 Readiness, Remediation & Auditing",
    ],
    strong: [
      "Maintain and leverage your attestation",
      "Keep your program current with annual review cycles and use it to win regulated clients who are leaving less-prepared MSPs.",
      "Managed Compliance (Manage phase)",
    ],
  },
  vendor: {
    gap: [
      "Know your supply chain",
      "Your clients inherit every vendor risk you carry. Stand up a vendor register, collect SOC reports for critical tools, subscribe to advisories with a response SLA, and inventory what you actually run.",
      "Risk Assessment (incl. vendor & supply-chain review)",
    ],
    watch: [
      "Tighten vendor oversight",
      "Move from onboarding-only review to an annual cycle, and bring subcontractor access under monitoring.",
      "Risk Assessment",
    ],
    strong: [
      "Vendor risk is under control",
      "Keep the register current and include vendor review in your annual risk assessment.",
      "Managed Cybersecurity (Manage phase)",
    ],
  },
  proof: {
    gap: [
      "Be able to prove it",
      "This is where deals stall and audits fail. Build a questionnaire answer library, centralize evidence in a GRC platform, institute quarterly access reviews, and get an independent assessment on record.",
      "vCISO Services + Security Maturity Level Assessment (GRC platform)",
    ],
    watch: [
      "Organize the evidence you already have",
      "You can produce proof, but slowly. Centralizing policies, logs, and reviews in one place turns a scramble into a same-week response.",
      "Security Maturity Level Assessment + GRC platform onboarding",
    ],
    strong: [
      "Proof is a competitive advantage",
      "Put your evidence pack in front of prospects proactively — it shortens sales cycles with regulated clients.",
      "Managed Compliance (Manage phase)",
    ],
  },
};

/** Maturity level summary and detail copy, keyed by level number. */
export const LEVEL_TEXT: LevelText = {
  "1": [
    "Security depends on individual effort, not a program.",
    "Controls exist where a technician cared enough to set them up. Nothing is documented, tested, or provable. A client questionnaire, an insurer, or an incident would expose the gaps quickly.",
  ],
  "2": [
    "You respond to security demands as they arrive.",
    "Some controls are in place and some paperwork exists, but coverage is inconsistent and evidence is scattered. You can answer questions — after a scramble.",
  ],
  "3": [
    "A defined program exists; it is not yet proven.",
    "Policies and baselines are written and mostly followed. The gap is verification: testing, independent assessment, and organized evidence.",
  ],
  "4": [
    "You run a managed security practice.",
    "Controls are documented, reviewed, and largely evidenced. Attestation or a final set of tested processes would make the program fully defensible.",
  ],
  "5": [
    "Your practice operates at the level clients and auditors expect of a security partner.",
    "Documented, tested, independently verified, and provable on request. The opportunity now is to sell it.",
  ],
};

/** Shipped defaults; the admin edits a versioned copy of this in the database. */
export const DEFAULT_SCORING: Scoring = {
  weights: {
    tooling: 15,
    lifecycle: 15,
    ir: 20,
    compliance: 15,
    vendor: 15,
    proof: 20,
  },
  levels: [
    {
      n: 1,
      name: "Initial",
      min: 0,
    },
    {
      n: 2,
      name: "Reactive",
      min: 30,
    },
    {
      n: 3,
      name: "Defined",
      min: 50,
    },
    {
      n: 4,
      name: "Managed",
      min: 70,
    },
    {
      n: 5,
      name: "Optimized",
      min: 85,
    },
  ],
  gapBelow: 50,
  watchBelow: 75,
};

/** Illustrative partner economics — set per partner agreement. */
export const DEFAULT_ECON = {
  marginPct: 25,
  referralPct: 10,
  minClients: 1,
};

export const MSP_ASSESSMENT_VERSION = '1.0';
