#!/usr/bin/env node
/**
 * Extracts the question banks, copy tables and defaults from the reference
 * logic files into typed TypeScript modules under `lib/data/`.
 *
 *   npm run generate:data
 *
 * The reference files are the source of truth for every string, so the data is
 * lifted by executing them against a stubbed prototype runtime rather than
 * retyped — a transcription slip in 24 questions × 4 options × 2 assessments
 * would be invisible in review.
 */

import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

/** Runs a reference logic file with the prototype runtime stubbed out. */
function loadLogic(file) {
  const src = fs.readFileSync(path.join(root, 'reference', file), 'utf8');
  const sandbox = {
    DCLogic: class {
      constructor() {}
      setState() {}
    },
    localStorage: {
      getItem: () => null,
      setItem: () => {},
      removeItem: () => {},
    },
    console,
    window: { scrollTo() {} },
  };
  vm.createContext(sandbox);
  vm.runInContext(`${src}\n;globalThis.__instance = new Component({});`, sandbox);
  return sandbox.__instance;
}

/** Serializes a value as a TypeScript literal with stable formatting. */
function ts(value, indent = 0) {
  const pad = '  '.repeat(indent);
  const padIn = '  '.repeat(indent + 1);
  if (value === null) return 'null';
  if (typeof value === 'string') return JSON.stringify(value);
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    const simple = value.every((v) => typeof v === 'string' || typeof v === 'number');
    if (simple && JSON.stringify(value).length < 100) return JSON.stringify(value);
    return `[\n${value.map((v) => padIn + ts(v, indent + 1)).join(',\n')},\n${pad}]`;
  }
  const keys = Object.keys(value);
  if (keys.length === 0) return '{}';
  const body = keys
    .map((k) => `${padIn}${/^[A-Za-z_$][\w$]*$/.test(k) ? k : JSON.stringify(k)}: ${ts(value[k], indent + 1)}`)
    .join(',\n');
  return `{\n${body},\n${pad}}`;
}

const header = (source) => `// AUTO-GENERATED by tools/extract-data.mjs — do not edit by hand.
// Source of truth: reference/${source}
// Regenerate with \`npm run generate:data\`.
`;

// ---------------------------------------------------------------- MSP data
const msp = loadLogic('msp-logic.js');

const mspOut = `${header('msp-logic.js')}
import type { Domain, MspQuestion, RecTable, LevelText, Scoring } from '@/lib/types';

/** Six assessment domains, in presentation order. */
export const DOMAINS: Domain[] = ${ts(msp.DOMAINS)};

/** 24 questions; option order is best → worst and points are \`3 - index\`. */
export const QUESTIONS: MspQuestion[] = ${ts(msp.QUESTIONS)};

/** Recommendation copy per domain per status. */
export const RECS: RecTable = ${ts(msp.RECS)};

/** Maturity level summary and detail copy, keyed by level number. */
export const LEVEL_TEXT: LevelText = ${ts(msp.LEVEL_TEXT)};

/** Shipped defaults; the admin edits a versioned copy of this in the database. */
export const DEFAULT_SCORING: Scoring = ${ts(msp.DEFAULT_SCORING)};

/** Illustrative partner economics — set per partner agreement. */
export const DEFAULT_ECON = ${ts(msp.DEFAULT_ECON)};

export const MSP_ASSESSMENT_VERSION = '1.0';
`;

// ------------------------------------------------------------- Client data
const client = loadLogic('client-logic.js');

const clientOut = `${header('client-logic.js')}
import type { CsfFunction, ClientQuestion, RecTable, Tier, Vertical, Qualification } from '@/lib/types';

/** The six NIST CSF 2.0 functions, in presentation order. */
export const FNS: CsfFunction[] = ${ts(client.FNS)};

/** 24 questions; \`{FW} {DATA} {AUD} {SYSTEMS}\` are substituted from the vertical. */
export const QUESTIONS: ClientQuestion[] = ${ts(client.QUESTIONS)};

/** The seven verticals a brand can be pointed at. */
export const VERTICALS: Record<string, Vertical> = ${ts(client.VERTICALS)};

/** Recommendation copy per CSF function per status. */
export const RECS: RecTable = ${ts(client.RECS)};

/** Readiness tiers by minimum score. */
export const TIERS: Tier[] = ${ts(client.TIERS)};

/** Shipped defaults for the lead qualification rule; admin-editable. */
export const DEFAULT_QUAL: Qualification = ${ts(client.DEFAULT_QUAL)};

/** Framework chips offered on the lead gate. */
export const FW_CHIPS: string[] = ${ts(client.FW_CHIPS)};

export const CLIENT_ASSESSMENT_VERSION = 'client-1.0';
`;

// -------------------------------------------------------------- Brand data
const brandsOut = `${header('msp-logic.js + client-logic.js')}
import type { Brand } from '@/lib/types';

/**
 * Seed brands. \`inovo\` is the default tenant; \`msp-security-services\` is the
 * sample partner that the prototype's brand switcher demonstrated.
 *
 * Nothing brand-related may be hardcoded in a component — read these through
 * the brand context, which resolves the tenant per request by hostname.
 */
export const SEED_BRANDS: Record<string, Brand> = ${ts({
  inovo: {
    ...msp.DEFAULT_BRANDS.inovo,
    // The prototype loaded the logo relatively; it is served from /public here.
    logo: '/assets/inovo-logo.png',
    slug: 'inovo',
    hostnames: ['assess.inovois.com'],
    vertical: 'cmmc',
    routing: { model: 'direct', notify: ['sales@inovois.com'] },
    econ: msp.DEFAULT_ECON,
  },
  partner: {
    ...msp.DEFAULT_BRANDS.partner,
    // Empty in the prototype, which falls back to the initials text mark.
    logo: msp.DEFAULT_BRANDS.partner.logo || null,
    slug: 'msp-security-services',
    hostnames: ['security.partnerdomain.example'],
    vertical: 'hipaa',
    routing: {
      model: 'co-delivery',
      notify: [msp.DEFAULT_BRANDS.partner.email, 'sales@inovois.com'],
    },
    econ: msp.DEFAULT_ECON,
  },
})};

/**
 * The client assessment overrides one label for the partner brand: the
 * prototype rewrites "Book my security review" to "Book my advisory session"
 * on the client report. Reproduced here so the report copy is unchanged.
 */
export const CLIENT_REPORT_CTA_OVERRIDE: Record<string, string> = ${ts({
  partner: 'Book my advisory session',
})};
`;

fs.mkdirSync(path.join(root, 'lib', 'data'), { recursive: true });
fs.writeFileSync(path.join(root, 'lib', 'data', 'msp.ts'), mspOut);
fs.writeFileSync(path.join(root, 'lib', 'data', 'client.ts'), clientOut);
fs.writeFileSync(path.join(root, 'lib', 'data', 'brands.ts'), brandsOut);

console.log(`  lib/data/msp.ts      ${msp.QUESTIONS.length} questions, ${msp.DOMAINS.length} domains`);
console.log(`  lib/data/client.ts   ${client.QUESTIONS.length} questions, ${Object.keys(client.VERTICALS).length} verticals, ${client.TIERS.length} tiers`);
console.log(`  lib/data/brands.ts   ${Object.keys(msp.DEFAULT_BRANDS).length} seed brands`);
