#!/usr/bin/env node
/**
 * Generates the screen components under `components/generated/` from the
 * approved prototypes in `reference/`.
 *
 * Each entry below names a line range in a `.dc.html` file that is a
 * tag-balanced block, and the component file it becomes. The ranges are the
 * top-level `<sc-if>` screens of the prototypes; see `tools/dc2jsx.mjs` for the
 * markup transformation itself.
 *
 *   npm run generate:screens
 *
 * The generated files are committed so the app builds without the reference
 * folder, but they are never edited by hand — change the prototype (or this
 * generator) and regenerate, then run `npm run fidelity`.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { convert } from './dc2jsx.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = path.join(root, 'components', 'generated');

const SCREENS = [
  { file: 'MSP Assessment.dc.html', from: 41, to: 322, name: 'MspLanding' },
  { file: 'MSP Assessment.dc.html', from: 327, to: 523, name: 'MspAssessment' },
  { file: 'MSP Assessment.dc.html', from: 528, to: 694, name: 'MspAdmin' },
  { file: 'MSP Assessment.dc.html', from: 699, to: 749, name: 'MspNotes' },
  { file: 'Client Assessment.dc.html', from: 43, to: 360, name: 'ClientPage' },
  { file: 'Client Assessment.dc.html', from: 365, to: 431, name: 'ClientAdmin' },
];

/** Which view-model each screen reads. `null` means the screen is static copy. */
const VIEW_MODEL_TYPE = {
  MspLanding: 'MspVals',
  MspAssessment: 'MspVals',
  MspAdmin: 'MspAdminVals',
  MspNotes: null,
  ClientPage: 'ClientVals',
  ClientAdmin: 'ClientAdminVals',
};

function sliceLines(text, from, to) {
  const lines = text.split('\n');
  return lines.slice(from - 1, to).join('\n');
}

let generated = 0;
fs.mkdirSync(OUT_DIR, { recursive: true });

for (const screen of SCREENS) {
  const src = fs.readFileSync(path.join(root, 'reference', screen.file), 'utf8');
  const block = sliceLines(src, screen.from, screen.to);
  const jsx = convert(block);
  const valsType = VIEW_MODEL_TYPE[screen.name];
  const usesFragment = jsx.includes('<Fragment');

  const imports = [
    usesFragment ? "import { Fragment } from 'react';" : null,
    valsType ? `import type { ${valsType} } from '@/lib/view-models/types';` : null,
  ]
    .filter(Boolean)
    .join('\n');

  const signature = valsType
    ? `${screen.name}({ V }: { V: ${valsType} })`
    : `${screen.name}()`;

  const out = `// AUTO-GENERATED by tools/generate-screens.mjs — do not edit by hand.
// Source: reference/${screen.file} lines ${screen.from}-${screen.to}
// Regenerate with \`npm run generate:screens\`, then verify with \`npm run fidelity\`.
/* eslint-disable react/no-unescaped-entities, @next/next/no-img-element */
'use client';

${imports}

export default function ${signature} {
  return (
${jsx
  .split('\n')
  .map((l) => (l.trim() ? '    ' + l : l))
  .join('\n')}
  );
}
`;

  fs.writeFileSync(path.join(OUT_DIR, `${screen.name}.tsx`), out);
  generated++;
  process.stdout.write(`  generated components/generated/${screen.name}.tsx (${screen.file} ${screen.from}-${screen.to})\n`);
}

process.stdout.write(`\n${generated} screen component(s) generated.\n`);
